apiVersion: v1
kind: Pod
metadata:
  name: ong-api
  labels:
    app: ong-api
spec:
  containers:
  - name: ong-api
    image: ong-api:latest
    ports:
    - containerPort: 3000
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
