name: Standard

on:
  push:
    branches:
      - main
      - develop
      - feature/*
      - hotfix/*
    paths-ignore:
      - "**/*.md"
  pull_request:
    branches:
      - main
      - develop
    paths-ignore:
      - "**/*.md"

jobs:

  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: Cache Node Modules
        uses: actions/cache@v2
        id: cache
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test:cov

      - name: Sonar Analysis
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  ci_docker:
    name: CI Docker
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - name: Build
        run: echo "Building image"
      - name: Push
        run: echo "Pushing image"

  cd:
    name: CD
    runs-on: ubuntu-latest
    needs: [ci, ci_docker]
    if: ${{ success() && github.event_name != 'pull_request' && github.ref == 'refs/heads/main' }}
    steps:
      - name: Deploy Infra
        run: echo "Deploying to production"
      - name: Deploy App
        run: echo "Deploying to production"
